apiVersion: v1
kind: Service
metadata:
  name: gooaye-summary-service
spec:
  type: LoadBalancer # 讓 GKE 自動分配外部 IP
  selector:
    app: gooaye-summary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
